apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-operator
  template:
    metadata:
      labels:
        app: vault-operator
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: ${VAULT_OPERATOR_SERVICE_ACCOUNT}
      imagePullSecrets: [${VAULT_OPERATOR_IMAGE_PULL_SECRET}]
      securityContext:
        # ensure that s/a token is readable xref: https://issues.k8s.io/70679
        fsGroup: 65535
      containers:
      - name: operator
        image: ${VAULT_OPERATOR_DOCKER_REGISTRY}/vault-operator:${VAULT_OPERATOR_IMAGE_TAG}
        imagePullPolicy: ${VAULT_OPERATOR_IMAGE_PULL_POLICY}
        args:
        - run
        - --v=3
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-mutating-webhook=${VAULT_OPERATOR_ENABLE_MUTATING_WEBHOOK}
        - --enable-validating-webhook=${VAULT_OPERATOR_ENABLE_VALIDATING_WEBHOOK}
        - --bypass-validating-webhook-xray=${VAULT_OPERATOR_BYPASS_VALIDATING_WEBHOOK_XRAY}
        - --use-kubeapiserver-fqdn-for-aks=${VAULT_OPERATOR_USE_KUBEAPISERVER_FQDN_FOR_AKS}
        - --enable-analytics=${VAULT_OPERATOR_ENABLE_ANALYTICS}
        - --cluster-name=${VAULT_OPERATOR_CLUSTER_NAME}
        - --metrics-exporter.url=${METRICS_EXPORTER_API_URL}
        - --metrics-exporter.interval=${METRICS_EXPORTER_INTERVAL}
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: "100m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_NAME
          value: vault-operator
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: ${METRICS_EXPORTER_LICENSE_SECRET}
              key: jwt
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: vault-operator-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      priorityClassName: ${VAULT_OPERATOR_PRIORITY_CLASS}
---
# kube lacks the service serving cert signer, so provide a manual secret for it
apiVersion: v1
kind: Secret
metadata:
  name: vault-operator-apiserver-cert
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_SERVING_CERT}
  tls.key: ${TLS_SERVING_KEY}
---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: vault-operator
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: vault-operator
