apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "vault-operator.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if eq .Values.monitoring.agent "prometheus.io/builtin" }}
  annotations:
    prometheus.io/scrap: "true"
    {{- if .Values.monitoring.operator }}
    prometheus.io/operator_path: "/metrics"
    prometheus.io/operator_port: "8443"
    prometheus.io/operator_scheme: "https"
    {{- end }}
  {{- end }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: "{{ template "vault-operator.name" . }}"
    release: "{{ .Release.Name }}"
