# GKE returns Major:"1", Minor:"10+"
{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.kubevault.com
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: vaultservers.validators.kubevault.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.kubevault.com/v1alpha1/vaultservervalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - kubevault.com
    apiVersions:
    - "*"
    resources:
    - vaultservers
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.authorization.kubedb.com
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "vault-operator.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: databaseaccessrequests.validators.authorization.kubedb.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.authorization.kubedb.com/v1alpha1/databaseaccessrequestvalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - authorization.kubedb.com
    apiVersions:
    - "*"
    resources:
    - databaseaccessrequests
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.engine.kubevault.co
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "vault-operator.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: awsaccesskeyrequests.validators.engine.kubevault.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.engine.kubevault.com/v1alpha1/awsaccesskeyrequestvalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - engine.kubevault.com
    apiVersions:
    - "*"
    resources:
    - awsaccesskeyrequests
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
- name: gcpaccesskeyrequests.validators.engine.kubevault.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.engine.kubevault.com/v1alpha1/gcpaccesskeyrequestvalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - engine.kubevault.com
    apiVersions:
    - "*"
    resources:
    - gcpaccesskeyrequests
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
- name: azureaccesskeyrequests.validators.engine.kubevault.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.engine.kubevault.com/v1alpha1/azureaccesskeyrequests
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
    - operations:
        - CREATE
        - UPDATE
      apiGroups:
        - engine.kubevault.com
      apiVersions:
        - "*"
      resources:
        - azureaccesskeyrequests
  failurePolicy: Fail
  {{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
  {{- end }}
{{ end }}
