{{- $caCrt := "" }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- if .Values.apiserver.servingCerts.generate }}
{{- $ca := genCA "ca" 3650 }}
{{- $cn := include "vault-operator.fullname" . -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $altName3 := printf "%s.%s.svc.cluster.local" $cn .Release.Namespace }}
{{- $server := genSignedCert $cn nil (list $altName1 $altName2 $altName3) 3650 $ca }}
{{- $caCrt =  b64enc $ca.Cert }}
{{- $serverCrt = b64enc $server.Cert }}
{{- $serverKey = b64enc $server.Key }}
{{- else }}
{{- $caCrt = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.caCrt }}
{{- $serverCrt = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.serverCrt }}
{{- $serverKey = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.serverKey }}
{{- end }}
{{- if or .Values.apiserver.enableMutatingWebhook .Values.apiserver.enableValidatingWebhook }}
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.mutators.kubevault.com
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
spec:
  group: mutators.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "vault-operator.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.validators.kubevault.com
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
spec:
  group: validators.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "vault-operator.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.validators.engine.kubevault.com
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
spec:
  group: validators.engine.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "vault-operator.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-operator.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $serverCrt }}
  tls.key: {{ $serverKey }}
---
{{ $promNamespace:= default .Release.Namespace .Values.monitoring.prometheus.namespace }}
{{- if (and (ne $promNamespace .Release.Namespace) .Values.monitoring.operator) }}
# if operator monitoring is enabled and prometheus namespace is different than operator
# create the above secret in prometheus namespace too.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-operator.fullname" . }}-apiserver-cert
  namespace: {{ $promNamespace }}
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $serverCrt }}
  tls.key: {{ $serverKey }}
---
{{- end }}
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "vault-operator.fullname" . }}-apiserver-extension-server-authentication-reader
  namespace: kube-system
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "vault-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "vault-operator.fullname" . }}-apiserver-auth-delegator
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ template "vault-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
