apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault-operator.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      serviceAccountName: {{ template "vault-operator.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      {{- end }}
      containers:
      - name: kubectl
        image: {{ .Values.cleaner.registry }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}
        command:
          - sh
          - -c
          - "sleep 2; kubectl delete validatingwebhookconfigurations validators.kubevault.com || true;kubectl delete validatingwebhookconfigurations validators.engine.kubevault.com || true; kubectl delete mutatingwebhookconfiguration mutators.kubevault.com || true"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Never
