apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevault:core:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - kubevault.com
  - catalog.kubevault.com
  - policy.kubevault.com
  - appcatalog.appscode.com
  - engine.kubevault.com
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevault:core:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - kubevault.com
  resources:
  - vaultservers
  verbs: ["*"]
- apiGroups:
  - policy.kubevault.com
  resources:
  - vaultpolicies
  - vaultpolicybindings
  verbs: ["*"]
- apiGroups:
  - engine.kubevault.com
  resources:
  - secretengines
  - databaseaccessrequests
  - mongodbroles
  - mysqlroles
  - postgresroles
  - awsroles
  - awsaccesskeyrequests
  - gcproles
  - gcpaccesskeyrequests
  - azureroles
  - azureaccesskeyrequests
  verbs: ["*"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs: ["*"]
- apiGroups:
  - catalog.kubevault.com
  resources:
  - vaultserverversions
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevault:core:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - kubevault.com
  resources:
  - vaultservers
  verbs: ["get", "list", "watch"]
- apiGroups:
  - policy.kubevault.com
  resources:
  - vaultpolicies
  - vaultpolicybindings
  verbs: ["get", "list", "watch"]
- apiGroups:
  - engine.kubevault.com
  resources:
  - secretengines
  - databaseaccessrequests
  - mongodbroles
  - mysqlroles
  - postgresroles
  - awsroles
  - awsaccesskeyrequests
  - gcproles
  - gcpaccesskeyrequests
  - azureroles
  - azureaccesskeyrequests
  verbs: ["get", "list", "watch"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs: ["get", "list", "watch"]
- apiGroups:
  - catalog.kubevault.com
  resources:
  - vaultserverversions
  verbs: ["get", "list", "watch"]
